### PR TITLE
Some important improvements (requested by our users) and Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by douglascrp**

### CODE REVIEW

**Comment by alexanderonlyoffice** [comment]
douglascrp@6c79c10c9cf48f079f6281ed58f18255ef06f9cb, could you please describe the issue with embedded mode more precisely, as the embedded mode has nothing to do with mobile UI. We would like to receive your feedback on this to be able to analyze the problem that might come across with the spreadsheets and the embedded mode.

**Comment by douglascrp** [comment]
Ok, this is the problem.

When the spreadsheet has many tabs, it becomes impossible to access them, as the zoom in and out buttons appear over them, and it is not possible to click.

In order to give you an example, check the image below:

image

This is from the customer's server, when using the preview.

**Comment by Rita-Bubnova** [comment]
@douglascrp, I can confirm - this is bug, issue 48069 in our private issue tracker.

**Comment by Rita-Bubnova** [comment]
> @douglascrp, I can confirm - this is bug, issue 48069 in our private issue tracker.

This bug fixed (https://github.com/ONLYOFFICE/web-apps/commit/b22e621318e49f5853736a3c191c6993a56b0333)  in future release.

**Pull request merged**
