### PR TITLE
Update onlyoffice-module-context.xml

### PR DESCRIPTION
**Pull request by guisup**

### CODE REVIEW

**Comment by svgta1** [comment]
Don't do this update : it's block the co-editing.

**Comment by ibnpetr** [comment]
@guisup Could you please specify any details regarding this PR,
What is it for?

**Comment by guisup** [comment]
Hi,

It's just a syntax error : the ":" before onlyoffice is wrong.
See :
https://docs.alfresco.com/5.0/concepts/dev-extensions-share-evaluators.html


regards,


<gsupercz@gmail.com>


Le lun. 6 juil. 2020 à 10:19, Alexey Mikheev <notifications@github.com> a
écrit :

**Comment by Eloncase** [comment]
this change is unnecessary

**Pull request closed without merging**
